---
title: "About the Workshop"
---

## Dates and Time 
xx June, 2021 - xx June, 2021 (Sat and Sun)

9 am - 4 pm (US Eastern Time)

There are a total four 3-hour sessions. Morning sessions run from 9 am to 12 noon, and afternoon sessions run from 1 pm - 4 pm. 

## Format 
Fully online via Zoom (synchronous)

## Fees
The workshop itself is free. But, we ask that participants donate no less than $50 (or an equivalent amount in any local currency) to a charity that has been offering help during the COVID pandemic. It can be a church, a food bank, a charity. All registrants will be asked to upload a receipt of their donation before we confirm your registration. 

## Materials
We will take advantage of open data and code generously shared by researchers in the field. So, we will be playing with data that we have good background knowledge. Participants can also read the publication(s) associated with the data ahead of time to familiarize themselves with the context. Additional code used in the workshop will be made available on this website as well. 

## Content 
### Day 1 Morning
* An Overview of R
* Basics in R
  * Working Directory
  * Packages
  * Importing and Exporting Data
  * Data Types
  * Data Frames

### Day 1 Afternoon
* Descriptive Statistics in R
  * mean, standard deviation, confidence intervals and more
  * Descriptives by groups

### Day 2 Morning
* Data Visualization using ggplot2
  * Scatter plots
  * Line graphs for group comparisons and more

### Day 2 Afternoon
* Fitting the First Regression Models in R
  * Modeling Fitting
  * Assumption checks
  * Interpreting and Reporting the Results